=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end

def divisors_of i
  divs = [1, i]
  y = i
  (2..(i ** 0.5).to_i).each do |x|  
    if i % x == 0
      y = i / x
      divs << x
      divs << y if x != y
    end
  end
  divs
end


index = 1
start_time = Time.now
triangle = 1

while divisors_of(triangle).count < 500
  index += 1
  triangle += index
end

p "> 500 factors: #{triangle} in #{Time.now - start_time} s"







